#!/usr/bin/env python

import argparse
parser = argparse.ArgumentParser()

parser.add_argument("-p","--path", required=True, help="path to the sensor")
parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")

args = parser.parse_args()

if args.verbose:
    print "pulling sensor value from path {}".format(args.path)
else:
    print args.path
